"""Prometheus metrics configuration for the application.

This module sets up and configures Prometheus metrics for monitoring the application.
"""

from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
)
from starlette_prometheus import (
    PrometheusMiddleware,
    metrics,
)

# Request metrics
http_requests_total = Counter("http_requests_total", "Total number of HTTP requests", ["method", "endpoint", "status"])

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds", "HTTP request duration in seconds", ["method", "endpoint"]
)

# Database metrics
db_connections = Gauge("db_connections", "Number of active database connections")

llm_inference_duration_seconds = Histogram(
    "llm_inference_duration_seconds",
    "Time spent processing LLM inference",
    ["model"],
    buckets=[0.1, 0.3, 0.5, 1.0, 2.0, 5.0],
)


llm_stream_duration_seconds = Histogram(
    "llm_stream_duration_seconds",
    "Time spent processing LLM stream inference",
    ["model"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
)

session_names_generated_total = Counter(
    "session_names_generated_total",
    "Total session names generated by the LLM",
    ["status"],  # "success" | "error"
)

# --- Sprint 1: supervisor routing -------------------------------------------
# One decision per turn. `route` is the capability route chosen, `matched_rule`
# the rule that chose it (or the fallback), `multi_intent` whether the turn was
# decomposed into more than one route.
routing_decisions_total = Counter(
    "sprintflow_routing_decisions_total",
    "Supervisor routing decisions",
    ["route", "matched_rule", "multi_intent"],
)

routing_latency_seconds = Histogram(
    "sprintflow_routing_latency_seconds",
    "Time the supervisor spent deciding a route (no model call on the common path)",
    buckets=[0.0001, 0.00025, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.05],
)

# Incremented only if routing ever consults a model. The rule-based supervisor
# never does, so the ratio of this counter to routing_decisions_total is the
# measured escalation rate the orchestration report cites.
routing_model_calls_total = Counter(
    "sprintflow_routing_model_calls_total",
    "Routing decisions that needed a model call",
    ["route"],
)

# --- Sprint 1: onboarding -----------------------------------------------------
onboarding_steps_total = Counter(
    "sprintflow_onboarding_steps_total",
    "Onboarding delivery outcomes",
    ["step_kind", "outcome"],  # outcome: sent | failed | halted | retry
)


def setup_metrics(app):
    """Set up Prometheus metrics middleware and endpoints.

    Args:
        app: FastAPI application instance
    """
    # Add Prometheus middleware
    app.add_middleware(PrometheusMiddleware)

    # Add metrics endpoint
    app.add_route("/metrics", metrics)
