"""Ceremony model — stores every scheduled meeting in the database.

Aligned with the team's DomainBase schema from data-model-migrations.
The ceremony type is now a FK to the CeremonyType lookup table, and
cancellation is tracked via the `status` field instead of a boolean.
"""

from datetime import datetime

from sqlalchemy import Column, DateTime
from sqlmodel import Field

from app.models.domain_base import DomainBase


class Ceremony(DomainBase, table=True):
    """One row = one scheduled ceremony (standup, planning, retro, etc.)

    Uses the shared DomainBase which provides created_at / updated_at
    with timezone-aware UTC timestamps.
    """

    # Primary key — auto-generated by the DB
    id: int | None = Field(default=None, primary_key=True)

    # Which cohort this ceremony belongs to (FK to the cohort table)
    cohort_id: int = Field(foreign_key="cohort.id", index=True)

    # What kind of ceremony — FK to the CeremonyType lookup table
    type_id: int = Field(foreign_key="ceremonytype.id")

    # Lifecycle status: "scheduled", "completed", "cancelled"
    status: str = Field(default="scheduled", nullable=False, index=True)

    # When the ceremony happens — always stored as UTC, timezone-aware
    scheduled_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True)
    )

    # Expected duration in minutes (optional)
    duration_mins: int | None = Field(default=None)

    # Who booked it (their user ID or email)
    organizer: str = Field(index=True)

    # Optional notes or agenda for the meeting
    agenda: str | None = Field(default=None)

    # Optional Mattermost channel to post the reminder in
    channel_id: str | None = Field(default=None)

    # The original text the organizer typed (useful for debugging)
    raw_input: str | None = Field(default=None)
