"""align domain models.

Revision ID: 2399bc07d56b
Revises: a86e08b1fcb3
Create Date: 2026-09-01 20:40:48.887751

"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2399bc07d56b'
down_revision: Union[str, Sequence[str], None] = 'a86e08b1fcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ceremony', sa.Column('organizer', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ceremony', sa.Column('agenda', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ceremony', sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ceremony', sa.Column('raw_input', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('ceremony', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ceremony', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_ceremony_cohort_id'), 'ceremony', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_ceremony_organizer'), 'ceremony', ['organizer'], unique=False)
    op.create_index(op.f('ix_ceremony_scheduled_at'), 'ceremony', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_ceremony_status'), 'ceremony', ['status'], unique=False)
    op.alter_column('cohort', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('cohort', 'ends_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('cohortmembership', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('cohortmembership_person_id_cohort_id_key'), 'cohortmembership', type_='unique')
    op.create_unique_constraint(None, 'cohortmembership', ['user_id', 'cohort_id', 'role_id'])
    op.drop_constraint(op.f('cohortmembership_person_id_fkey'), 'cohortmembership', type_='foreignkey')
    op.create_foreign_key(None, 'cohortmembership', 'user', ['user_id'], ['id'])
    op.drop_column('cohortmembership', 'person_id')
    op.drop_table('person')
    op.add_column('dailyprogress', sa.Column('what_i_did', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('dailyprogress', sa.Column('what_i_will_do', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('dailyprogress', sa.Column('blockers', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('dailyprogress', 'notes')
    op.add_column('escalation', sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('escalation', sa.Column('assigned_human_id', sa.Integer(), nullable=True))
    op.add_column('escalation', sa.Column('original_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('escalation', sa.Column('human_dm_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'escalation', 'user', ['assigned_human_id'], ['id'])
    op.alter_column('sprint', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sprint', 'ends_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_sprint_cohort_id'), 'sprint', ['cohort_id'], unique=False)
    op.add_column('user', sa.Column('mattermost_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_handle'), 'user', ['handle'], unique=True)
    op.create_index(op.f('ix_user_mattermost_user_id'), 'user', ['mattermost_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mattermost_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_handle'), table_name='user')
    op.drop_column('user', 'handle')
    op.drop_column('user', 'mattermost_user_id')
    op.drop_index(op.f('ix_sprint_cohort_id'), table_name='sprint')
    op.alter_column('sprint', 'ends_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sprint', 'starts_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'escalation', type_='foreignkey')
    op.drop_column('escalation', 'human_dm_thread_id')
    op.drop_column('escalation', 'original_thread_id')
    op.drop_column('escalation', 'assigned_human_id')
    op.drop_column('escalation', 'question')
    op.add_column('dailyprogress', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dailyprogress', 'blockers')
    op.drop_column('dailyprogress', 'what_i_will_do')
    op.drop_column('dailyprogress', 'what_i_did')
    op.add_column('cohortmembership', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cohortmembership', type_='foreignkey')
    op.create_foreign_key(op.f('cohortmembership_person_id_fkey'), 'cohortmembership', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'cohortmembership', type_='unique')
    op.create_unique_constraint(op.f('cohortmembership_person_id_cohort_id_key'), 'cohortmembership', ['person_id', 'cohort_id'])
    op.drop_column('cohortmembership', 'user_id')
    op.alter_column('cohort', 'ends_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cohort', 'starts_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ceremony_status'), table_name='ceremony')
    op.drop_index(op.f('ix_ceremony_scheduled_at'), table_name='ceremony')
    op.drop_index(op.f('ix_ceremony_organizer'), table_name='ceremony')
    op.drop_index(op.f('ix_ceremony_cohort_id'), table_name='ceremony')
    op.alter_column('ceremony', 'scheduled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ceremony', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ceremony', 'raw_input')
    op.drop_column('ceremony', 'channel_id')
    op.drop_column('ceremony', 'agenda')
    op.drop_column('ceremony', 'organizer')
    op.create_table('person',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mattermost_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('handle', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('person_pkey')),
    sa.UniqueConstraint('handle', name=op.f('person_handle_key')),
    sa.UniqueConstraint('mattermost_user_id', name=op.f('person_mattermost_user_id_key'))
    )
    # ### end Alembic commands ###
