"""add channels table explicitly.

Revision ID: 5fe198326da8
Revises: e4ec613c2a56
Create Date: 2026-09-16 13:11:25.787257

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "5fe198326da8"
down_revision: Union[str, Sequence[str], None] = "e4ec613c2a56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
