"""Remove cohort_id completely.

Revision ID: 9199422f052d
Revises: b00000000000
Create Date: 2026-09-07 14:23:39.349955

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9199422f052d"
down_revision: Union[str, Sequence[str], None] = "b00000000000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ceremonies_cohort_id"), table_name="ceremonies")
    op.drop_constraint(op.f("fk_ceremonies_cohort_id_cohorts"), "ceremonies", type_="foreignkey")
    op.drop_column("ceremonies", "cohort_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ceremonies", sa.Column("cohort_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("fk_ceremonies_cohort_id_cohorts"), "ceremonies", "cohorts", ["cohort_id"], ["id"])
    op.create_index(op.f("ix_ceremonies_cohort_id"), "ceremonies", ["cohort_id"], unique=False)
    # ### end Alembic commands ###
