"""Add status defaults.

Revision ID: a86e08b1fcb3
Revises: ae9ba88585bc
Create Date: 2026-08-31 19:24:09.879446

"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a86e08b1fcb3'
down_revision: Union[str, Sequence[str], None] = 'ae9ba88585bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cohort', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cohortmembership', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cohortmembership', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dailyprogress', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sprint', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sprint', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dailyprogress', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cohortmembership', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cohortmembership', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cohort', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
