"""remove sprint_id from ceremonies.

Revision ID: e40272b244ca
Revises: c00000000002
Create Date: 2026-09-08 12:41:57.394737

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e40272b244ca"
down_revision: Union[str, Sequence[str], None] = "c00000000002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ceremonies_sprint_id"), table_name="ceremonies")
    op.drop_constraint(op.f("fk_ceremonies_sprint_id_sprints"), "ceremonies", type_="foreignkey")
    op.drop_column("ceremonies", "sprint_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ceremonies", sa.Column("sprint_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("fk_ceremonies_sprint_id_sprints"), "ceremonies", "sprints", ["sprint_id"], ["id"])
    op.create_index(op.f("ix_ceremonies_sprint_id"), "ceremonies", ["sprint_id"], unique=False)
    # ### end Alembic commands ###
