"""Refactor cohort to channel.

Revision ID: f3a7c288ced4
Revises: e40272b244ca
Create Date: 2026-09-09 12:17:14.897842

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f3a7c288ced4"
down_revision: Union[str, Sequence[str], None] = "e40272b244ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_roles",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("channel_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "channel_id", name="uq_channel_roles_user_channel"),
    )
    op.create_index(op.f("ix_channel_roles_channel_id"), "channel_roles", ["channel_id"], unique=False)
    op.create_index(op.f("ix_channel_roles_team_id"), "channel_roles", ["team_id"], unique=False)
    op.create_index(op.f("ix_channel_roles_user_id"), "channel_roles", ["user_id"], unique=False)
    op.drop_index(op.f("ix_cohort_memberships_cohort_id"), table_name="cohort_memberships")
    op.drop_index(op.f("ix_cohort_memberships_user_id"), table_name="cohort_memberships")
    op.drop_table("cohort_memberships")
    op.add_column(
        "escalation_tickets", sa.Column("team_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False)
    )
    op.add_column(
        "escalation_tickets", sa.Column("channel_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False)
    )
    op.drop_index(op.f("ix_escalation_tickets_cohort_id"), table_name="escalation_tickets")
    op.create_index(op.f("ix_escalation_tickets_channel_id"), "escalation_tickets", ["channel_id"], unique=False)
    op.create_index(op.f("ix_escalation_tickets_team_id"), "escalation_tickets", ["team_id"], unique=False)
    op.drop_constraint(op.f("fk_escalation_tickets_cohort_id_cohorts"), "escalation_tickets", type_="foreignkey")
    op.drop_column("escalation_tickets", "resolved_at")
    op.drop_column("escalation_tickets", "cohort_id")
    op.drop_column("escalation_tickets", "learner_channel_id")
    op.add_column("onboarding_steps", sa.Column("team_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column(
        "onboarding_steps", sa.Column("channel_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True)
    )
    op.drop_index(op.f("ix_onboarding_steps_cohort_id"), table_name="onboarding_steps")
    op.drop_constraint(op.f("uq_onboarding_steps_user_cohort_kind"), "onboarding_steps", type_="unique")
    op.create_index(op.f("ix_onboarding_steps_channel_id"), "onboarding_steps", ["channel_id"], unique=False)
    op.create_index(op.f("ix_onboarding_steps_team_id"), "onboarding_steps", ["team_id"], unique=False)
    op.create_unique_constraint(
        "uq_onboarding_steps_user_channel_kind",
        "onboarding_steps",
        ["user_id", "channel_id", "step_kind"],
        postgresql_nulls_not_distinct=True,
    )
    op.drop_constraint(op.f("fk_onboarding_steps_cohort_id_cohorts"), "onboarding_steps", type_="foreignkey")
    op.drop_column("onboarding_steps", "cohort_id")
    op.add_column("sprints", sa.Column("team_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.add_column("sprints", sa.Column("channel_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.drop_index(op.f("ix_sprints_cohort_id"), table_name="sprints")
    op.drop_constraint(op.f("uq_sprints_cohort_name"), "sprints", type_="unique")
    op.drop_index(op.f("ux_sprints_cohort_name_lower"), table_name="sprints")
    op.create_index(op.f("ix_sprints_channel_id"), "sprints", ["channel_id"], unique=False)
    op.create_index(op.f("ix_sprints_team_id"), "sprints", ["team_id"], unique=False)
    op.create_unique_constraint("uq_sprints_channel_name", "sprints", ["channel_id", "name"])
    op.create_index(
        "ux_sprints_channel_name_lower", "sprints", ["channel_id", sa.literal_column("lower(name)")], unique=True
    )
    op.drop_constraint(op.f("fk_sprints_cohort_id_cohorts"), "sprints", type_="foreignkey")
    op.drop_column("sprints", "cohort_id")
    op.drop_index(op.f("ix_cohorts_is_active"), table_name="cohorts")
    op.drop_index(op.f("ix_cohorts_mattermost_team_id"), table_name="cohorts")
    op.drop_index(op.f("ux_cohorts_name_lower"), table_name="cohorts")
    op.drop_table("cohorts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cohorts",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("mattermost_team_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("mattermost_channel_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
        sa.Column("starts_on", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("ends_on", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("deactivated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_cohorts_created_by_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cohorts")),
    )
    op.create_index(op.f("ux_cohorts_name_lower"), "cohorts", [sa.literal_column("lower(name::text)")], unique=True)
    op.create_index(op.f("ix_cohorts_mattermost_team_id"), "cohorts", ["mattermost_team_id"], unique=False)
    op.create_index(op.f("ix_cohorts_is_active"), "cohorts", ["is_active"], unique=False)
    op.add_column("sprints", sa.Column("cohort_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f("fk_sprints_cohort_id_cohorts"), "sprints", "cohorts", ["cohort_id"], ["id"])
    op.drop_index("ux_sprints_channel_name_lower", table_name="sprints")
    op.drop_constraint("uq_sprints_channel_name", "sprints", type_="unique")
    op.drop_index(op.f("ix_sprints_team_id"), table_name="sprints")
    op.drop_index(op.f("ix_sprints_channel_id"), table_name="sprints")
    op.create_index(
        op.f("ux_sprints_cohort_name_lower"),
        "sprints",
        ["cohort_id", sa.literal_column("lower(name::text)")],
        unique=True,
    )
    op.create_unique_constraint(op.f("uq_sprints_cohort_name"), "sprints", ["cohort_id", "name"])
    op.create_index(op.f("ix_sprints_cohort_id"), "sprints", ["cohort_id"], unique=False)
    op.drop_column("sprints", "channel_id")
    op.drop_column("sprints", "team_id")
    op.add_column("onboarding_steps", sa.Column("cohort_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("fk_onboarding_steps_cohort_id_cohorts"), "onboarding_steps", "cohorts", ["cohort_id"], ["id"]
    )
    op.drop_constraint("uq_onboarding_steps_user_channel_kind", "onboarding_steps", type_="unique")
    op.drop_index(op.f("ix_onboarding_steps_team_id"), table_name="onboarding_steps")
    op.drop_index(op.f("ix_onboarding_steps_channel_id"), table_name="onboarding_steps")
    op.create_unique_constraint(
        op.f("uq_onboarding_steps_user_cohort_kind"),
        "onboarding_steps",
        ["user_id", "cohort_id", "step_kind"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(op.f("ix_onboarding_steps_cohort_id"), "onboarding_steps", ["cohort_id"], unique=False)
    op.drop_column("onboarding_steps", "channel_id")
    op.drop_column("onboarding_steps", "team_id")
    op.add_column(
        "escalation_tickets",
        sa.Column("learner_channel_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    )
    op.add_column("escalation_tickets", sa.Column("cohort_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(
        "escalation_tickets",
        sa.Column("resolved_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_escalation_tickets_cohort_id_cohorts"), "escalation_tickets", "cohorts", ["cohort_id"], ["id"]
    )
    op.drop_index(op.f("ix_escalation_tickets_team_id"), table_name="escalation_tickets")
    op.drop_index(op.f("ix_escalation_tickets_channel_id"), table_name="escalation_tickets")
    op.create_index(op.f("ix_escalation_tickets_cohort_id"), "escalation_tickets", ["cohort_id"], unique=False)
    op.drop_column("escalation_tickets", "channel_id")
    op.drop_column("escalation_tickets", "team_id")
    op.create_table(
        "cohort_memberships",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("cohort_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=32),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("assigned_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"], ["users.id"], name=op.f("fk_cohort_memberships_assigned_by_id_users")
        ),
        sa.ForeignKeyConstraint(["cohort_id"], ["cohorts.id"], name=op.f("fk_cohort_memberships_cohort_id_cohorts")),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_cohort_memberships_role_id_roles")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_cohort_memberships_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cohort_memberships")),
        sa.UniqueConstraint("user_id", "cohort_id", name=op.f("uq_cohort_memberships_user_cohort")),
    )
    op.create_index(op.f("ix_cohort_memberships_user_id"), "cohort_memberships", ["user_id"], unique=False)
    op.create_index(op.f("ix_cohort_memberships_cohort_id"), "cohort_memberships", ["cohort_id"], unique=False)

    op.drop_index(op.f("ix_channel_roles_user_id"), table_name="channel_roles")
    op.drop_index(op.f("ix_channel_roles_team_id"), table_name="channel_roles")
    op.drop_index(op.f("ix_channel_roles_channel_id"), table_name="channel_roles")
    op.drop_table("channel_roles")
    # ### end Alembic commands ###
